### ISSUE TITLE
Assignment 1 ready for grading!

### ISSUE THREAD

**Issue by Erik9997** [SES-5215-F2020/erikfichter-quant#1]

**Comment by c-voulgaris** [comment]
**Comments on code:**
**Line 8:** To avoid cluttering your output with package messages, consider replacing this line with ```{r load libraries, message=FALSE}

**Lines 26-41:** There is no reason to include these in your file. You needed them for your own reference, but the rest of the code runs fine without them.

**Line 43:** To avoid printing hundreds of lines of progress messages, replace this line with ``` {r, results = 'hide'}. This would also hide the table produced by line 63, so you'd need to put that line in a separate code chunk.

**Lines 63 - 70:** There's no need to include both the formatted table (line 63) and the unformatted table (line 70).

**Comments on content:**
You need to add an explicit statement indicating what your unit of analysis is. There may be some confusion here, since you've named your data frame "hh_data", but it's actually person-level data (because you've included person-level variables). You also need to explicitly say how many observations are in your dataset.
